# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PchomeCli < Formula
  desc "PChome 24h CLI for search, compare, and recommendations"
  homepage "https://github.com/oliyy/pchome-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oliyy/pchome-cli/releases/download/v0.1.0/pchome-cli_0.1.0_darwin_x86_64.tar.gz"
      sha256 "4e1a7885217b85dfbca516d0b10ce6eb67fdfed2ab04d83a7857e88c9ccbc4fb"

      define_method(:install) do
        bin.install "pchome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oliyy/pchome-cli/releases/download/v0.1.0/pchome-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "a59231251584bcc73bc1a126224bf8e9e7ee266316cfdea7f64a846628216649"

      define_method(:install) do
        bin.install "pchome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliyy/pchome-cli/releases/download/v0.1.0/pchome-cli_0.1.0_linux_x86_64.tar.gz"
      sha256 "770b48fe54553e2cfa4468fdd33d4c697e7ab412142f7d525a3b030121f26155"
      define_method(:install) do
        bin.install "pchome"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliyy/pchome-cli/releases/download/v0.1.0/pchome-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "caeb30e9bc989081f3ec48c70b87cbeabba6f01b76f99d14fe5d43b57fe7580a"
      define_method(:install) do
        bin.install "pchome"
      end
    end
  end

  test do
    system "#{bin}/pchome", "--version"
  end
end
