# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PchomeCli < Formula
  desc "PChome 24h CLI for search, compare, and recommendations"
  homepage "https://github.com/oliyy/pchome-cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oliyy/pchome-cli/releases/download/v0.0.1/pchome-cli_0.0.1_darwin_x86_64.tar.gz"
      sha256 "349431aac95a7c1d73994d14d9b3715aa75395c710b698718e789973908aaf83"

      define_method(:install) do
        bin.install "pchome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oliyy/pchome-cli/releases/download/v0.0.1/pchome-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "44246c2d65ef3836563df11e26e9d8e82456356b71bb09f118a5995913bf4490"

      define_method(:install) do
        bin.install "pchome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliyy/pchome-cli/releases/download/v0.0.1/pchome-cli_0.0.1_linux_x86_64.tar.gz"
      sha256 "9116d15ae7e58c7b66d50082d0dc793937780bf439501decd9f57ce4e4a5216e"
      define_method(:install) do
        bin.install "pchome"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliyy/pchome-cli/releases/download/v0.0.1/pchome-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "c131beed48ee300532bca3c88f823c2313b5f4cbdbc5ffe1850300b9698800af"
      define_method(:install) do
        bin.install "pchome"
      end
    end
  end

  test do
    system "#{bin}/pchome", "--version"
  end
end
